#! /bin/sh

sxhkd &
compton --config ~/.config/compton.conf &
xinput set-prop 12 274 1 &
feh --no-fehbg --bg-fill ~/Wallpapers/female_deathknight.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          15

bspc config normal_border_color     "#15aabf"
bspc config active_border_color     "#15aabf"
bspc config focused_border_color    "#3bc9db"
bspc config presel_feedback_color   "#3bc9db"

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
